---
title: "Exploratory data analysis"
format: html
date: "`r format(Sys.time(), '%d %B, %Y')`"    
toc: true
toc-expand: 3
editor: source
editor_options: 
  chunk_output_type: console
knitr:
  opts_chunk: 
    echo: true
    message: false
    warning: false
    code-fold: true
    include: true
    collapse: true
---

```{r}
#| label: setup-env

# Set-up R environment
rm(list=ls())

library(tidyverse)
library(readxl)
library(DT)
library(arsenal)
library(gtsummary)
library(RColorBrewer)
library(edgeR)
library(plotly)
library(kableExtra)
library(ggpmisc)
library(ggalluvial)

# load functions
#source("functions.R")

# load data
file <- "../data/processed/data.RData"
load(file)



```

```{r}
# set graphical theme
mycols <- brewer.pal(8, "Set1")
mycols2 <- brewer.pal(8, "Dark2")

text_size <- 8
mytheme <- theme(legend.title = element_blank(), 
                 legend.text = element_text(size = text_size),
                 panel.grid.major = element_blank(), 
                 panel.grid.minor = element_blank(),
                 axis.text = element_text(size = text_size),
                 axis.title = element_text(size = text_size), 
                 strip.background =element_rect(fill=c("white"), colour = "white"), 
                 strip.text = element_text(colour = 'black', size = text_size + 1))
```


# Introduction

- V2: luteal phase
- V3: follicular phase

# Clinical data

```{r}
#| label: tbl-summary-stats
#| tbl-cap: "Summary statistics of BV, Nugent Score and Age for V2 and V3 overlapping samples."
#| results: asis

# clinical data
df_clin <- df_meta_subset %>%
  left_join(df_meta) 

# extend with delta BV and Nugent scores (V3: folicular phase - V2: luteal phase)
df_clin_ext <- df_clin %>%
  mutate(delta_Nugent = Nugent_v2 - Nugent_v3) %>%
  mutate(delta_BV = as.numeric(BV_v2) - as.numeric(BV_v3)) %>%
  mutate(delta_BV = as.factor(delta_BV))

# clinical data in long format
df_v2 <- df_clin %>%
  select(PatID, BV_v2, Nugent_v2, age) %>%
  mutate(ID = paste(PatID, "_V2", sep="")) %>%
  mutate(V = "V2") %>%
  rename(BV = BV_v2, 
         Nugent = Nugent_v2) %>%
  relocate(V, .after = PatID) %>%
  relocate(ID)

df_v3 <- df_clin %>%
  select(PatID, BV_v3, Nugent_v3, age) %>%
  mutate(ID = paste(PatID, "_V3", sep="")) %>%
  mutate(V = "V3") %>%
  rename(BV = BV_v3, 
         Nugent = Nugent_v3) %>%
  relocate(V, .after = PatID) %>%
  relocate(ID)

df_clin_long <- rbind(df_v2, df_v3) %>%
  mutate(V = factor(V, levels = c("V3", "V2")))

df_clin_long %>% 
  dplyr::select(!c(PatID, ID)) %>%
  tbl_summary(by = V,
              missing_text = "(Missing)") %>%
  as_kable_extra(booktabs = TRUE) %>%
  kable_styling()

```

## Nugent Score

::: {.panel-tabset}

### Histogram
```{r}
#| label: fig-NS-histogram
#| fig-cap: "Histogram of Nugent scores for V2 and V3 samples."

df_clin_long %>%
  ggplot(aes(x=Nugent, fill = V)) + 
  geom_histogram(color = "black", alpha = 0.7) +
  facet_wrap(~V, ncol = 1) + 
  xlab("Nugent score") +
  scale_fill_manual(values = mycols2) + 
  theme_bw() + 
  mytheme

```

### Density
```{r}
#| label: fig-NS-density
#| fig-cap: "Density plot of Nugent scores for V2 and V3 samples."

df_clin_long %>%
  ggplot(aes(x=Nugent, group = V, color = V)) + 
  geom_density(size = 1.2) + 
  scale_color_manual(values = mycols2) + 
  xlab("Nugent score") + 
  theme_bw() + 
  mytheme
```

### Density (change V2 - V3)
```{r}
#| label: fig-NS-density-delta
#| fig-cap: "Distribution of a change of Nugent scores between V3 (follicular phase) and V2 (luteal phase)."

df_clin_ext %>%
  ggplot(aes(x=delta_Nugent)) + 
  geom_histogram(color = "black", fill = mycols[2], alpha = 0.7) +
  scale_color_manual(values = mycols2) + 
  xlab("Nugent score") + 
  theme_bw() + 
  mytheme

```

:::

## BV
```{r}
#| label: tbl-BV-change
#| tbl-cap: "Change of BV category between V3 and V2 phases."
#| results: asis

df_clin_ext %>% 
  dplyr::select(delta_BV) %>%
  tbl_summary(missing_text = "(Missing)") %>%
  as_kable_extra(booktabs = TRUE) %>%
  kable_styling()
```


```{r}

df_clin_ext
```

